package model.daoModels;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
import signing.Organization;
// KEEP INCLUDES END
/**
 * Entity mapped to table "SIGNING_ORGANIZATION".
 */
public class SigningOrganization implements java.io.Serializable {

    private Long id;
    private String email;
    private String name;
    private String url;
    private String uniqueSlug;
    private String slug;
    private java.util.Date createdAt;
    private java.util.Date expiresAt;
    private java.util.Date modifiedAt;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public SigningOrganization() {
    }

    public SigningOrganization(Long id) {
        this.id = id;
    }

    public SigningOrganization(Long id, String email, String name, String url, String uniqueSlug, String slug, java.util.Date createdAt, java.util.Date expiresAt, java.util.Date modifiedAt) {
        this.id = id;
        this.email = email;
        this.name = name;
        this.url = url;
        this.uniqueSlug = uniqueSlug;
        this.slug = slug;
        this.createdAt = createdAt;
        this.expiresAt = expiresAt;
        this.modifiedAt = modifiedAt;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getUrl() {
        return url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

    public String getUniqueSlug() {
        return uniqueSlug;
    }

    public void setUniqueSlug(String uniqueSlug) {
        this.uniqueSlug = uniqueSlug;
    }

    public String getSlug() {
        return slug;
    }

    public void setSlug(String slug) {
        this.slug = slug;
    }

    public java.util.Date getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(java.util.Date createdAt) {
        this.createdAt = createdAt;
    }

    public java.util.Date getExpiresAt() {
        return expiresAt;
    }

    public void setExpiresAt(java.util.Date expiresAt) {
        this.expiresAt = expiresAt;
    }

    public java.util.Date getModifiedAt() {
        return modifiedAt;
    }

    public void setModifiedAt(java.util.Date modifiedAt) {
        this.modifiedAt = modifiedAt;
    }

    // KEEP METHODS - put your custom methods here

    //region setup methods

    /**
     * @param uniqueSlug Slug unique to only one model
     * @param session Session to use
     * @return Unique Model with passed slug
     */
    static public SigningOrganization getModelForUniqueSlug(String uniqueSlug, DaoSession session){

        SigningOrganizationDao dao = session.getSigningOrganizationDao();
        return dao.queryBuilder()
                .where(SigningOrganizationDao.Properties.UniqueSlug.eq(uniqueSlug))
                .unique();
    }

    /**
     * Sets this model's values to that of the passed Organization and saves it to the database
     * @param org Organization with which to set the values of this model
     * @param session Session to use
     */
    public void updateWithOrganization(Organization org, DaoSession session){

        setToOrganization(org);
        if(id != null && id > -1) {
            session.getSigningOrganizationDao().update(this);
        }
        else{
            session.getSigningOrganizationDao().insert(this);
        }
    }

    /**
     * Sets this model's values to that of the passed organization
     * @param org Organization to use for this model's data
     */
    private void setToOrganization(Organization org){
        this.email = org.email;
        this.name = org.name;
        this.url = org.url;
        this.uniqueSlug = org.slug;
        this.createdAt = org.createdAt;
        this.expiresAt = org.expiresAt;
        this.modifiedAt = org.modifiedAt;
    }

    //endregion

    @Override
    public String toString() {
        return "SigningOrganization{" +
                "createdAt=" + createdAt +
                ", email='" + email + '\'' +
                ", expiresAt=" + expiresAt +
                ", id=" + id +
                ", modifiedAt=" + modifiedAt +
                ", name='" + name + '\'' +
                ", slug='" + slug + '\'' +
                ", uniqueSlug='" + uniqueSlug + '\'' +
                ", url='" + url + '\'' +
                '}';
    }
    // KEEP METHODS END

}
