package model.daoModels;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
import signing.Organization;
// KEEP INCLUDES END
/**
 * Entity mapped to table SIGNING_ORGANIZATION.
 */
public class SigningOrganization implements java.io.Serializable {

    private Long id;
    private String email;
    private String name;
    private String url;
    private String uniqueSlug;
    private String slug;
    private java.util.Date createdAt;
    private java.util.Date expiresAt;
    private java.util.Date modifiedAt;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public SigningOrganization() {
    }

    public SigningOrganization(Long id) {
        this.id = id;
    }

    public SigningOrganization(Long id, String email, String name, String url, String uniqueSlug, String slug, java.util.Date createdAt, java.util.Date expiresAt, java.util.Date modifiedAt) {
        this.id = id;
        this.email = email;
        this.name = name;
        this.url = url;
        this.uniqueSlug = uniqueSlug;
        this.slug = slug;
        this.createdAt = createdAt;
        this.expiresAt = expiresAt;
        this.modifiedAt = modifiedAt;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getUrl() {
        return url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

    public String getUniqueSlug() {
        return uniqueSlug;
    }

    public void setUniqueSlug(String uniqueSlug) {
        this.uniqueSlug = uniqueSlug;
    }

    public String getSlug() {
        return slug;
    }

    public void setSlug(String slug) {
        this.slug = slug;
    }

    public java.util.Date getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(java.util.Date createdAt) {
        this.createdAt = createdAt;
    }

    public java.util.Date getExpiresAt() {
        return expiresAt;
    }

    public void setExpiresAt(java.util.Date expiresAt) {
        this.expiresAt = expiresAt;
    }

    public java.util.Date getModifiedAt() {
        return modifiedAt;
    }

    public void setModifiedAt(java.util.Date modifiedAt) {
        this.modifiedAt = modifiedAt;
    }

    // KEEP METHODS - put your custom methods here


    static public SigningOrganization getModelForUniqueSlug(String uniqueSlug, DaoSession session){

        SigningOrganizationDao dao = session.getSigningOrganizationDao();
        SigningOrganization model = dao.queryBuilder()
                .where(SigningOrganizationDao.Properties.UniqueSlug.eq(uniqueSlug))
                .unique();

        return (model == null)? null : model;
    }

    public void createWithOrganization(Organization org, DaoSession session){

        setToOrganization(org);
        session.getSigningOrganizationDao().insert(this);
    }

    public void updateWithOrganization(Organization org, DaoSession session){

        setToOrganization(org);
        session.getSigningOrganizationDao().update(this);
    }

    private void setToOrganization(Organization org){
        this.email = org.email;
        this.name = org.name;
        this.url = org.url;
        this.uniqueSlug = org.slug;
        this.createdAt = org.createdAt;
        this.expiresAt = org.expiresAt;
        this.modifiedAt = org.modifiedAt;
    }
    // KEEP METHODS END

}
